export APPHOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
export SNORKELHOME="$APPHOME/snorkel"
export DDBIOLIBHOME="$APPHOME/ddbiolib"
echo "Application home directory: $APPHOME"
echo "Snorkel home directory: $SNORKELHOME"
echo "ddbiolib home directory: $DDBIOLIBHOME"
export PYTHONPATH="$PYTHONPATH:$APPHOME:$DDBIOLIBHOME:$SNORKELHOME:$SNORKELHOME/treedlib"
export PATH="$PATH:$SNORKELHOME:$DDBIOLIBHOME:$SNORKELHOME/treedlib"
echo "Environment variables set!"
